spring:
  profiles:
    active: dev

  datasource:
    hupubao:
      jdbc-url: jdbc:sqlite:db/hupubao.db
      driver-class-name: org.sqlite.JDBC
    logging:
      jdbc-url: jdbc:sqlite:db/logging.db
      driver-class-name: org.sqlite.JDBC

  devtools:
    restart:
      enabled: false

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout:


mybatis:
  type-aliases-package: org.spring.springboot.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mapper/hupubao/*.xml,classpath*:mybatis/mapper/logging/*.xml

mapper:
  mappers: win.hupubao.utils.mybatis.MyMapper
  not-empty: false


logging:
  level:
    win.hupubao: debug
    win.hupubao.mapper.logging: info

server:
  port: 2015


auth:
  excludes:
    - user.login
    - captcha.create
access:
  origin:
    allow-origins:
    - http://127.0.0.1:8010
    - http://manager.hupubao.win

--- #dev环境文档

spring:
  profiles: dev

  redis:
    password: 123456

  domain: http://127.0.0.1:8888
...
--- #prod环境文档

spring:
  profiles: prod
  redis:
    password: 123456

  domain: http://hupubao.win
...