spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1


  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout:


mybatis:
  type-aliases-package: org.spring.springboot.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mapper/hupubao/*.xml,classpath*:mybatis/mapper/logging/*.xml

mapper:
  mappers: win.hupubao.utils.mybatis.MyMapper
  not-empty: false


logging:
  level:
    win.hupubao: debug
    win.hupubao.mapper.logging: info

server:
  port: 2015
  tomcat:
      max-threads: 10

auth:
  excludes:
    - user.login
    - captcha.create
access:
  origin:
    allow-origins:
    - http://127.0.0.1:8010
    - http://127.0.0.1:8011
    - http://hupubao.win
    - https://hupubao.win
    - http://www.hupubao.win
    - https://www.hupubao.win
    - http://manager.hupubao.win
    - https://manager.hupubao.win
    - https://v2.hupubao.win
    - http://v2.hupubao.win
    - https://ysdxz207.github.io

--- #dev环境文档

spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hupubao
    username: hupubao
    password: 123456

  redis:
    password: 123456

  domain: http://127.0.0.1:2015
...
--- #prod环境文档

spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hupubao
    username: hupubao
    password: ysdxz207@hupubao.win
  redis:
    password: 123456

  domain: http://hupubao.win
...