spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlite:src/main/resources/db/hupubao.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  devtools:
    restart:
      enabled: false

mybatis:
  type-aliases-package: org.spring.springboot.domain
mapper:
  mappers: win.hupubao.utils.mybatis.MyMapper
  not-empty: false
server:
  port: 8888


