spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:sqlite:db/hupubao.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

  devtools:
    restart:
      enabled: false

  redis:
      database: 0
      host: 127.0.0.1
      password: 123456
      port: 6379
      timeout:


mybatis:
  type-aliases-package: org.spring.springboot.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
mapper:
  mappers: win.hupubao.utils.mybatis.MyMapper
  not-empty: false


logging:
  level:
    win.hupubao: debug

server:
  port: 8888


auth:
  excludes:
    - user.login
    - captcha.create
access:
  origin:
    allow-origins:
    - http://127.0.0.1:8010
